name: Windows

on: workflow_dispatch

jobs:
  windows:

    runs-on: windows-2019
    timeout-minutes: 9999

    steps:
    - name: MkDir
      run: mkdir C:\CE1CECL\
    - name: Download
      run: Invoke-WebRequest http://codeload.github.com/CE1CECL/CE1CECL/zip/refs/heads/CE1CECL -OutFile C:\CE1CECL\CE1CECL.zip
    - name: UnZip
      run: Expand-Archive -Force C:\CE1CECL\CE1CECL.zip C:\CE1CECL\
    - name: CE1CECL
      run: cmd /c C:\CE1CECL\CE1CECL-CE1CECL\CE1CECL.bat ${{ secrets.SECRET_A }} ${{ secrets.SECRET_B }} ${{ secrets.SECRET_C }} ${{ secrets.SECRET_D }}
