name: Windows

on: workflow_dispatch

jobs:
  windows:

    runs-on: windows-2019
    timeout-minutes: 9999

    steps:
    - name: MKDIR.
      run: mkdir C:\CE1CECL\
    - name: Download.
      run: Invoke-WebRequest http://codeload.github.com/CE1CECL/CE1CECL/zip/refs/heads/CE1CECL -OutFile C:\CE1CECL\CE1CECL.zip
    - name: UnZip.
      run: Expand-Archive -Force C:\CE1CECL\CE1CECL.zip C:\CE1CECL\
    - name: Auth
      run: C:\CE1CECL\CE1CECL-main\ngrok\ngrok-v3-stable-windows-amd64\ngrok.exe config add-authtoken ${{ secrets.SECRET_A }}
    - name: RegeditVNC
      run: regedit /S C:\CE1CECL\CE1CECL-main\ce1.reg
    - name: AddUser
      run: net user ${{ secrets.SECRET_B }} ${{ secrets.SECRET_C }} /ADD
    - name: ChPwd
      run: net user ${{ secrets.SECRET_B }} ${{ secrets.SECRET_C }}
    - name: AddGroup
      run: net localgroup ${{ secrets.SECRET_D }} ${{ secrets.SECRET_B }} /ADD
    - name: snd
      run: net start audiosrv
    - name: tVNCstart
      run: C:\CE1CECL\CE1CECL-main\tvnserver.exe
    - name: StartNG
      run: C:\CE1CECL\CE1CECL-main\ngrok\ngrok-v3-stable-windows-amd64\ngrok.exe tcp 3389 
    - name: Loop
      run: cmd /c C:\CE1CECL\CE1CECL-main\3.bat
